type: object
properties:
  allowMultibooking:
    type: integer
    minimum: -1
    maximum: 999
  enableGuestBooking:
    type: boolean
  enableVerifiedBooking:
    type: boolean
  enableInsuranceBooking:
    type: boolean
    default: true